version: '3.7'

services:
  mysql-db:
    image: mysql:latest
    ports:
      - '3307:3306'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: warehouse