name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    - name: Run Tests
    working-directory: 
      run: |
        pip install -r requirements.txt
        pytest tests/